# Generated by Django 5.0.6 on 2024-06-13 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jeu_petit_prince', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='account',
            new_name='account_name',
        ),
    ]
