# Generated by Django 5.0.6 on 2024-06-21 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jeu_petit_prince', '0004_alter_profile_account_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birds_collected',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='games',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='item_1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='item_2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='item_3',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='total_score',
        ),
    ]
